# Generated by Django 4.1.2 on 2023-06-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('Qualification', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('passport_size_photo', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
