# Generated by Django 4.1.2 on 2023-06-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='passport_size_photo',
        ),
    ]
